name: ShooterGame
version: ${projectVersion}
main: net.qilla.shootergame.ShooterGame
api-version: '1.20'
load: STARTUP
author: Qilla
commands:
  GetGun:
    description: Get a specific gun type and tier
    usage: /getgun
    aliases: [gg]
  GetArmor:
    description: Get a specific armor type
    usage: /getarmor
    aliases: [ga]
  GetBlock:
    description: Get a specific custom block
    usage: /getblock
    aliases: [gb]