name: ZombieShooter
version: ${projectVersion}
main: net.qilla.zombieshooter.ZombieShooter
api-version: '1.20'
load: STARTUP
author: Qilla
commands:
  GetGun:
    description: Get a specific gun type and tier
    usage: /getgun
    aliases: [gg]